SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TRIGGER TGR_CALCULA_IDADE 
   ON  CONTATO 
   AFTER INSERT,UPDATE
AS 
BEGIN
    DECLARE 
	@DATA_NASC DATETIME,
	@DATA_ATUAL DATETIME,
	@IDADE INT,
	@ID INT

	SET @DATA_ATUAL = (SELECT GETDATE())
	SELECT @DATA_NASC = Data_nasc, @ID = Id_Cliente from inserted

	UPDATE CONTATO SET Idade = (YEAR(@DATA_ATUAL) - YEAR(@DATA_NASC)) WHERE Id_Cliente = @ID 	

END
GO